Repository leboncoin/spark-web, pull requests merged in 2023-09, with the labels that each got.

#1430 fix(theme-utils): update neutral related tokens based on latest Figma iteration
  packages/utils/theme/src/defaultTheme.ts
  packages/utils/theme/src/defaultThemeDark.ts
Labels: Bug

#1444 feat(text-link): text-link package (experimental)
  package-lock.json
  packages/components/text-link/.npmignore
  packages/components/text-link/package.json
  packages/components/text-link/src/TextLink.doc.mdx
  packages/components/text-link/src/TextLink.stories.tsx
  packages/components/text-link/src/TextLink.test.tsx
  packages/components/text-link/src/TextLink.tsx
  packages/components/text-link/src/index.ts
  packages/components/text-link/tsconfig.json
  packages/components/text-link/vite.config.ts
Labels: in discussion, component

#1474 fix(dialog): release stable dialog
  packages/components/dialog/src/Dialog.stories.tsx
Labels: blocked, Design review

#1514 docs: add story expand assist icon
  .storybook/preview.jsx
  tailwind.config.cjs
Labels: hacktoberfest-accepted
