Repository leboncoin/spark-web, pull requests merged in 2023-07, with the labels that each got.

#979 style(checkbox): resync sizing according to design specs
  packages/components/checkbox/src/CheckboxGroup.styles.ts
  packages/components/checkbox/src/CheckboxInput.styles.ts
Labels: bug

#980 style(radio-group): resync according to design specs
  packages/components/radio-group/src/Radio.tsx
  packages/components/radio-group/src/RadioGroup.doc.mdx
  packages/components/radio-group/src/RadioGroup.stories.tsx
  packages/components/radio-group/src/RadioGroup.styles.ts
  packages/components/radio-group/src/RadioGroup.tsx
  packages/components/radio-group/src/RadioGroupContext.tsx
  packages/components/radio-group/src/RadioGroupProvider.tsx
  packages/components/radio-group/src/RadioIndicator.styles.ts
  packages/components/radio-group/src/RadioIndicator.tsx
  packages/components/radio-group/src/RadioInput.styles.ts
  packages/components/radio-group/src/RadioInput.tsx
Labels: bug

#999 fix: typo in peerDependency package name, from tailwind to tailwindcss
  packages/components/spinner/package.json
  packages/components/visually-hidden/package.json
Labels: bug

#1012 docs: add question to faq section
  documentation/using-spark/FAQ.mdx
Labels: documentation

#1020 feat: add height transition to FAQ component
  documentation/helpers/FAQ/Answer.tsx
  documentation/helpers/FAQ/Item.tsx
  documentation/helpers/FAQ/Question.tsx
  documentation/helpers/FAQ/context.tsx
Labels: documentation, enhancement

#1019 chore(icons): remove country flags
  packages/components/icons/assets/FlagAT.svg
  packages/components/icons/assets/FlagBE.svg
  packages/components/icons/assets/FlagBR.svg
  packages/components/icons/assets/FlagBY.svg
  packages/components/icons/assets/FlagCH.svg
  packages/components/icons/assets/FlagCL.svg
  packages/components/icons/assets/FlagCO.svg
  packages/components/icons/assets/FlagDO.svg
  packages/components/icons/assets/FlagES.svg
  packages/components/icons/assets/FlagFI.svg
  packages/components/icons/assets/FlagFR.svg
  packages/components/icons/assets/FlagHU.svg
  packages/components/icons/assets/FlagID.svg
  packages/components/icons/assets/FlagIE.svg
  packages/components/icons/assets/FlagIT.svg
  packages/components/icons/assets/FlagMA.svg
  packages/components/icons/assets/FlagMX.svg
  packages/components/icons/assets/FlagMY.svg
  packages/components/icons/assets/FlagPT.svg
  packages/components/icons/assets/FlagSE.svg
  packages/components/icons/assets/FlagTN.svg
  packages/components/icons/assets/FlagVN.svg
  packages/components/icons/scripts/build.mjs
  packages/components/icons/scripts/utils/optimize.mjs
  packages/components/icons/src/icons/FlagAt.tsx
  packages/components/icons/src/icons/FlagBe.tsx
  packages/components/icons/src/icons/FlagBr.tsx
  packages/components/icons/src/icons/FlagBy.tsx
  packages/components/icons/src/icons/FlagCh.tsx
  packages/components/icons/src/icons/FlagCl.tsx
  packages/components/icons/src/icons/FlagCo.tsx
  packages/components/icons/src/icons/FlagDo.tsx
  packages/components/icons/src/icons/FlagEs.tsx
  packages/components/icons/src/icons/FlagFi.tsx
  packages/components/icons/src/icons/FlagFr.tsx
  packages/components/icons/src/icons/FlagHu.tsx
  packages/components/icons/src/icons/FlagId.tsx
  packages/components/icons/src/icons/FlagIe.tsx
  packages/components/icons/src/icons/FlagIt.tsx
  packages/components/icons/src/icons/FlagMa.tsx
  packages/components/icons/src/icons/FlagMx.tsx
  packages/components/icons/src/icons/FlagMy.tsx
  packages/components/icons/src/icons/FlagPt.tsx
  packages/components/icons/src/icons/FlagSe.tsx
  packages/components/icons/src/icons/FlagTn.tsx
  packages/components/icons/src/icons/FlagVn.tsx
  packages/components/icons/src/index.ts
  packages/components/icons/src/tags.ts
Labels: ✅ Ready, Size XS

#1038 docs: add faq questions
  documentation/using-spark/FAQ.mdx
Labels: documentation

#1049 docs(checkbox/radio group): add implementation and guidance for custom checkbox/radio group components
  packages/components/checkbox/src/Checkbox.doc.mdx
  packages/components/checkbox/src/Checkbox.stories.tsx
  packages/components/radio-group/src/RadioGroup.doc.mdx
  packages/components/radio-group/src/RadioGroup.stories.tsx
Labels: documentation

#1060 🐤 Chip stage 5
  packages/components/chip/src/Chip.doc.mdx
  packages/components/chip/src/Chip.stories.tsx
  packages/components/chip/src/Chip.styles.tsx
  packages/components/chip/src/Chip.tsx
  packages/components/chip/src/useChipElement.tsx
Labels: canary 🐤

#1112 refactor: update eslint rules for unused vars
  .eslintrc.cjs
  packages/components/icons/scripts/build.mjs
  packages/components/icons/scripts/utils/componentize.mjs
  packages/components/icons/scripts/utils/indexify.mjs
  packages/components/icons/scripts/utils/tagify.mjs
  packages/components/icons/scripts/utils/writeFile.mjs
  packages/components/popover/src/PopoverHeader.tsx
  packages/components/radio-group/src/RadioGroup.tsx
  packages/components/switch/src/Switch.tsx
  packages/utils/cli/src/generate/generators/TemplateGenerator.mjs
  packages/utils/cli/src/generate/templates/component/src/[Component.stories.tsx].js
  packages/utils/cli/src/generate/templates/component/src/[Component.styles.ts].js
  packages/utils/cli/src/generate/templates/component/src/[Component.styles.tsx].js
  packages/utils/cli/src/generate/validators/NameValidator.mjs
  packages/utils/cli/test/spark-generate.test.ts
  packages/utils/tailwind-plugins/animations/index.js
  packages/utils/tailwind-plugins/utilities/index.js
  packages/utils/tailwind-plugins/variants/index.js
Labels: bug, enhancement

#1114 🐤 coulours badge
  package-lock.json
  packages/components/badge/package.json
  packages/components/badge/src/Badge.stories.tsx
  packages/components/badge/src/BadgeItem.styles.tsx
Labels: canary 🐤

#1113 🐤 colours button
  package-lock.json
  packages/components/button/package.json
  packages/components/button/src/Button.stories.tsx
  packages/components/button/src/Button.styles.tsx
  packages/components/button/src/Button.tsx
  packages/components/button/src/variants/contrast.ts
  packages/components/button/src/variants/filled.ts
  packages/components/button/src/variants/ghost.ts
  packages/components/button/src/variants/outlined.ts
  packages/components/button/src/variants/tinted.ts
Labels: canary 🐤

#1131 docs: improve faq section
  documentation/using-spark/FAQ.mdx
Labels: documentation
