Repository leboncoin/spark-web, pull requests merged in 2023-06, with the labels that each got.

#809 refactor(switch): fix and improve accessibility on switch component
  package-lock.json
  packages/components/switch/package.json
  packages/components/switch/src/Switch.doc.mdx
  packages/components/switch/src/Switch.stories.tsx
  packages/components/switch/src/Switch.test.tsx
  packages/components/switch/src/Switch.tsx
  packages/components/switch/src/SwitchInput.tsx
  packages/components/switch/src/SwitchLabel.styles.ts
  packages/components/switch/src/SwitchLabel.tsx
Labels: enhancement

#831 refactor(button): upd outlined variant border size
  package-lock.json
  packages/components/button/src/Button.styles.tsx
Labels: enhancement

#855 fix(radio): fix and improve a11y on radio
  package-lock.json
  packages/components/radio/package.json
  packages/components/radio/src/Radio.doc.mdx
  packages/components/radio/src/Radio.stories.tsx
  packages/components/radio/src/Radio.test.tsx
  packages/components/radio/src/Radio.tsx
  packages/components/radio/src/RadioLabel.styles.tsx
  packages/components/radio/src/RadioLabel.tsx
Labels: enhancement

#832 fix(checkbox): fix and improve a11y on checkbox
  package-lock.json
  packages/components/checkbox/package.json
  packages/components/checkbox/src/Checkbox.doc.mdx
  packages/components/checkbox/src/Checkbox.stories.tsx
  packages/components/checkbox/src/Checkbox.test.tsx
  packages/components/checkbox/src/Checkbox.tsx
  packages/components/checkbox/src/CheckboxInput.tsx
  packages/components/checkbox/src/CheckboxLabel.styles.ts
  packages/components/checkbox/src/CheckboxLabel.tsx
Labels: enhancement

#914 fix: undo radix label bump
  package-lock.json
  packages/components/form-field/package.json
  packages/components/label/package.json
  packages/components/radio-group/package.json
Labels: bug

#920 fix: code snippets on component docs
  packages/components/form-field/src/index.ts
  packages/components/label/src/index.ts
  packages/components/radio-group/src/index.ts
  packages/components/tabs/src/Tabs.tsx
Labels: bug

#889 chore: add a11y script using aXe tooling
  .github/workflows/quality.yml
  bin/check-a11y.js
  package-lock.json
  package.json
  packages/components/icons/src/index.stories.tsx
  packages/components/input/src/Input.stories.tsx
  packages/components/popover/src/Popover.stories.tsx
  packages/components/slot/src/Slot.doc.mdx
  packages/components/slot/src/Slot.stories.tsx
  packages/components/tabs/src/Tabs.stories.tsx
  packages/components/tabs/src/TabsTrigger.tsx
  packages/components/textarea/src/Textarea.stories.tsx
Labels: enhancement

#951 fix(button): fix hover styles not being applied correctly when using the 'asChild' prop on button
  packages/components/button/src/variants/contrast.ts
  packages/components/button/src/variants/filled.ts
  packages/components/button/src/variants/ghost.ts
  packages/components/button/src/variants/outlined.ts
  packages/components/button/src/variants/tinted.ts
Labels: bug

#954 docs: fill up FAQ section with common questions
  documentation/GettingStarted.mdx
  documentation/helpers/FAQ/Answer.tsx
  documentation/helpers/FAQ/Item.tsx
  documentation/helpers/FAQ/Question.tsx
  documentation/helpers/FAQ/Root.tsx
  documentation/helpers/FAQ/context.tsx
  documentation/helpers/FAQ/index.tsx
  documentation/using-spark/FAQ.mdx
Labels: documentation

#965 docs: add ids to faq helper items for easier url sharing and navigation
  documentation/helpers/FAQ/Question.tsx
Labels: documentation, enhancement

#970 feat: update tcv package to be able to display position-related tokens
  package-lock.json
  package.json
Labels: documentation, enhancement
