Repository leboncoin/spark-web, pull requests merged in 2023-05, with the labels that each got.

#724 docs: add storylabel helper component
  documentation/helpers/StoryLabel/index.tsx
  packages/components/icon-button/src/IconButton.doc.mdx
  packages/components/icon-button/src/IconButton.stories.tsx
  packages/components/icon/src/Icon.stories.tsx
  packages/components/radio/src/Radio.doc.mdx
  packages/components/radio/src/Radio.stories.tsx
  packages/components/spinner/src/Spinner.stories.tsx
  packages/components/switch/src/Switch.stories.tsx
Labels: documentation

#774 refactor(tabs): add types export for tabs component
  packages/components/tabs/src/index.ts
Labels: enhancement

#781 docs: update docs with minor tweaks and improvements
  .storybook/preview-head.html
  documentation/GettingStarted.mdx
  documentation/using-spark/Setup.mdx
  documentation/using-spark/StylingOverview.mdx
  documentation/using-spark/TCV.mdx
Labels: documentation

#813 docs: add missing accessibility details on storybook
  packages/components/badge/src/Badge.doc.mdx
  packages/components/button/src/Button.doc.mdx
  packages/components/checkbox/src/Checkbox.doc.mdx
  packages/components/icon-button/src/IconButton.doc.mdx
  packages/components/label/src/Label.doc.mdx
  packages/components/radio/src/Radio.doc.mdx
  packages/components/switch/src/Switch.doc.mdx
  packages/components/tabs/src/Tabs.doc.mdx
  packages/components/visually-hidden/src/VisuallyHidden.doc.mdx
Labels: documentation, enhancement

#782 feat(switch): allowing formfield usage for switch component
  package-lock.json
  packages/components/switch/package.json
  packages/components/switch/src/Switch.doc.mdx
  packages/components/switch/src/Switch.stories.tsx
  packages/components/switch/src/Switch.test.tsx
  packages/components/switch/src/Switch.tsx
  packages/components/switch/src/SwitchInput.tsx
  packages/components/switch/src/SwitchLabel.tsx
Labels: enhancement
