Repository leboncoin/spark-web, pull requests merged in 2023-08, with the labels that each got.

#1125 🐤 Colours Checkbox
  package-lock.json
  packages/components/checkbox/package.json
  packages/components/checkbox/src/Checkbox.stories.tsx
  packages/components/checkbox/src/CheckboxInput.styles.ts
Labels: canary 🐤

#1124 🐤 Colours Tabs
  package-lock.json
  packages/components/tabs/package.json
  packages/components/tabs/src/Tabs.stories.tsx
  packages/components/tabs/src/TabsRoot.tsx
  packages/components/tabs/src/TabsTrigger.styles.ts
Labels: canary 🐤

#1121 🐤 Colours Spinner
  package-lock.json
  packages/components/spinner/package.json
  packages/components/spinner/src/Spinner.stories.tsx
  packages/components/spinner/src/Spinner.styles.tsx
Labels: canary 🐤

#1123 🐤 Colours Tag
  package-lock.json
  packages/components/tag/package.json
  packages/components/tag/src/Tag.stories.tsx
  packages/components/tag/src/Tag.styles.tsx
  packages/components/tag/src/Tag.tsx
  packages/components/tag/src/variants/filled.ts
  packages/components/tag/src/variants/outlined.ts
  packages/components/tag/src/variants/tinted.ts
Labels: canary 🐤

#1204 Canary/chip stage 6
  package-lock.json
  packages/components/button/src/Button.styles.tsx
  packages/components/chip/.npmignore
  packages/components/chip/package.json
  packages/components/chip/src/Chip.doc.mdx
  packages/components/chip/src/Chip.stories.tsx
  packages/components/chip/src/Chip.styles.tsx
  packages/components/chip/src/Chip.test.tsx
  packages/components/chip/src/Chip.tsx
  packages/components/chip/src/ChipClearButton.styles.tsx
  packages/components/chip/src/ChipClearButton.tsx
  packages/components/chip/src/ChipContent.tsx
  packages/components/chip/src/ChipLeadingIcon.tsx
  packages/components/chip/src/index.ts
  packages/components/chip/src/useChipContext.tsx
  packages/components/chip/src/useChipElement.tsx
  packages/components/chip/src/variants/dashed.ts
  packages/components/chip/src/variants/filled.ts
  packages/components/chip/src/variants/index.ts
  packages/components/chip/src/variants/outlined.ts
  packages/components/chip/src/variants/tinted.ts
  packages/components/chip/tsconfig.json
  packages/components/chip/vite.config.ts
  packages/utils/internal-utils/src/variants/constants.ts
Labels: canary 🐤

#1072 feat(input): input readonly styles
  packages/components/form-field/src/FormField.tsx
  packages/components/form-field/src/FormFieldContext.tsx
  packages/components/form-field/src/FormFieldControl.tsx
  packages/components/form-field/src/FormFieldProvider.tsx
  packages/components/input/src/Input.doc.mdx
  packages/components/input/src/Input.stories.tsx
  packages/components/input/src/Input.styles.ts
  packages/components/input/src/Input.test.tsx
  packages/components/input/src/Input.tsx
  packages/components/input/src/InputAddon.styles.ts
  packages/components/input/src/InputAddon.tsx
  packages/components/input/src/InputClearButton.tsx
  packages/components/input/src/InputGroup.styles.ts
  packages/components/input/src/InputGroup.tsx
  packages/components/input/src/InputGroupContext.ts
  packages/components/input/src/InputIcon.tsx
  packages/components/input/src/InputLeadingAddon.tsx
  packages/components/input/src/InputTrailingAddon.tsx
Labels: ✅ Ready

#1231 fix: use performance observer to ensure to scroll only when main thread is not blocked
  documentation/helpers/ToC/index.tsx
  package-lock.json
  package.json
Labels: bug

#1233 🐤 Chip Stage 7
  package-lock.json
  packages/components/chip/package.json
  packages/components/chip/src/Chip.doc.mdx
  packages/components/chip/src/Chip.stories.tsx
  packages/components/chip/src/Chip.styles.tsx
  packages/components/chip/src/Chip.tsx
  packages/components/chip/src/ChipClearButton.styles.tsx
  packages/components/chip/src/ChipClearButton.tsx
  packages/components/chip/src/useChipContext.tsx
  packages/components/chip/src/useChipElement.tsx
  packages/components/chip/src/variants/dashed.ts
  packages/components/chip/src/variants/filled.ts
  packages/components/chip/src/variants/outlined.ts
  packages/components/chip/src/variants/tinted.ts
Labels: canary 🐤

#1239 tag documentation
  packages/components/tag/src/Tag.doc.mdx
Labels: documentation

#1249 fix: main content layout issues
  .storybook/preview-head.html
  documentation/helpers/ToC/index.tsx
Labels: bug

#1251 docs: adapted custom ArgTypes table for mobile screens
  documentation/helpers/ArgTypes/index.tsx
  package-lock.json
Labels: documentation, enhancement

#1246 docs(form-field): updated docs to match latest agreements
  package-lock.json
  packages/components/form-field/src/FormField.doc.mdx
  packages/components/form-field/src/FormField.stories.tsx
Labels: documentation

#1252 feat(switch): add status styles and update docs
  packages/components/alert-dialog/src/AlertDialog.doc.mdx
  packages/components/checkbox/src/Checkbox.doc.mdx
  packages/components/checkbox/src/Checkbox.stories.tsx
  packages/components/switch/src/Switch.doc.mdx
  packages/components/switch/src/Switch.stories.tsx
  packages/components/switch/src/Switch.tsx
  packages/components/switch/src/SwitchInput.tsx
  packages/components/switch/src/SwitchLabel.tsx
  packages/components/switch/src/index.ts
Labels: documentation

#1270 feat: bump tcv to 1.7.9
  package-lock.json
  package.json
  packages/utils/tailwind-plugins/tailwind.config.viewer.misc.js
Labels: documentation, enhancement

#1234 docs(icon): updated docs to match latest agreement
  package-lock.json
  packages/components/icon/src/Icon.doc.mdx
Labels: documentation

#1272 feat(spinner): add full size to spinner
  packages/components/spinner/src/Spinner.doc.mdx
  packages/components/spinner/src/Spinner.stories.tsx
  packages/components/spinner/src/Spinner.styles.tsx
Labels: enhancement

#1242 fix(badge): do not display outline when badge is standalone
  package-lock.json
  packages/components/badge/src/Badge.doc.mdx
  packages/components/badge/src/Badge.stories.tsx
  packages/components/badge/src/BadgeItem.styles.tsx
Labels: bug, documentation

#1305 🐤 Stage 8 TEST
  package-lock.json
  packages/components/chip/src/Chip.test.tsx
  packages/components/chip/src/ChipClearButton.tsx
  packages/components/chip/src/useChipElement.tsx
Labels: canary 🐤

#1349 feat: remove misleading onChange prop on some components
  packages/components/checkbox/src/CheckboxInput.tsx
  packages/components/radio-group/src/RadioGroup.tsx
  packages/components/radio-group/src/RadioInput.tsx
Labels: Bug
