Repository leboncoin/spark-web, pull requests merged in 2024-03, with the labels that each got.

#1917 feat(snackbar): use external store to ensure single snackbar container
  packages/components/snackbar/src/Snackbar.test.tsx
  packages/components/snackbar/src/Snackbar.tsx
  packages/components/snackbar/src/useSnackbarGlobalStore.ts
Labels: component

#1916 feat(snackbar): add snackbar basic styles
  documentation/helpers/ArgTypes/index.tsx
  packages/components/snackbar/src/Snackbar.doc.mdx
  packages/components/snackbar/src/Snackbar.stories.tsx
  packages/components/snackbar/src/Snackbar.styles.ts
  packages/components/snackbar/src/Snackbar.test.tsx
  packages/components/snackbar/src/Snackbar.tsx
  packages/components/snackbar/src/SnackbarItem.styles.ts
  packages/components/snackbar/src/SnackbarItem.tsx
  packages/components/snackbar/src/index.ts
  packages/components/snackbar/src/snackbarVariants.ts
Labels: component

#1931 docs(snackbar): update snackbar docs
  documentation/helpers/ArgTypes/index.tsx
  package-lock.json
  packages/components/snackbar/package.json
  packages/components/snackbar/src/Snackbar.doc.mdx
  packages/components/snackbar/src/Snackbar.stories.tsx
  packages/components/snackbar/src/Snackbar.tsx
  packages/components/snackbar/src/SnackbarItem.styles.ts
  packages/components/snackbar/src/SnackbarItem.tsx
Labels: component

#1936 feat(dialog): implement focus capture and restoration in dialog component
  packages/components/dialog/src/Dialog.tsx
Labels: enhancement, component, dialog

#1967 feat(combobox): nowrap behaviour for multiselect
  package-lock.json
  package.json
  packages/components/combobox/package.json
  packages/components/combobox/src/Combobox.doc.mdx
  packages/components/combobox/src/Combobox.stories.tsx
  packages/components/combobox/src/ComboboxClearButton.tsx
  packages/components/combobox/src/ComboboxContext.tsx
  packages/components/combobox/src/ComboboxDisclosure.tsx
  packages/components/combobox/src/ComboboxInput.tsx
  packages/components/combobox/src/ComboboxLeadingIcon.tsx
  packages/components/combobox/src/ComboboxSelectedItems.tsx
  packages/components/combobox/src/ComboboxTrigger.styles.tsx
  packages/components/combobox/src/ComboboxTrigger.tsx
  packages/components/combobox/src/tests/multipleSelection.test.tsx
  packages/components/combobox/src/tests/test-utils.ts
  packages/components/combobox/src/useCombobox/multipleSelectionReducer.ts
  packages/components/combobox/src/utils/index.ts
  packages/components/combobox/src/utils/useWidthIncreaseCallback.ts
  vitest.setup.ts
Labels: component

#1922 feat(snackbar): add icon and snackbar actions
  package-lock.json
  packages/components/snackbar/src/Snackbar.doc.mdx
  packages/components/snackbar/src/Snackbar.stories.tsx
  packages/components/snackbar/src/Snackbar.test.tsx
  packages/components/snackbar/src/Snackbar.tsx
  packages/components/snackbar/src/SnackbarItem.tsx
  packages/components/snackbar/src/SnackbarItemAction.tsx
  packages/components/snackbar/src/SnackbarItemClose.tsx
  packages/components/snackbar/src/SnackbarItemContext.tsx
  packages/components/snackbar/src/SnackbarItemIcon.tsx
  packages/components/snackbar/src/index.ts
Labels: component

#1985 fix(combobox): content stacking display and positioning issues
  packages/components/dropdown/src/DropdownItems.tsx
  packages/components/dropdown/src/DropdownPopover.tsx
  packages/components/dropdown/src/useDropdown.ts
Labels: bug, component, dropdown

#2008 fix(dialog): use optional chaining operator to safely access node id
  packages/components/dialog/src/DialogContext.tsx
Labels: bug, component, dialog
