Repository leboncoin/spark-web, pull requests merged in 2024-02, with the labels that each got.

#1894 feat(snackbar): init package
  package-lock.json
  packages/components/snackbar/.npmignore
  packages/components/snackbar/LICENSE.md
  packages/components/snackbar/README.md
  packages/components/snackbar/package.json
  packages/components/snackbar/src/Snackbar.doc.mdx
  packages/components/snackbar/src/Snackbar.stories.tsx
  packages/components/snackbar/src/Snackbar.styles.ts
  packages/components/snackbar/src/Snackbar.test.tsx
  packages/components/snackbar/src/Snackbar.tsx
  packages/components/snackbar/src/index.ts
  packages/components/snackbar/tsconfig.json
  packages/components/snackbar/vite.config.ts
Labels: component

#1896 chore: upd spark generator template
  packages/utils/cli/src/generate/templates/component/[package.json].js
  packages/utils/cli/src/generate/templates/component/src/[Component.stories.tsx].js
Labels: enhancement, internal-utils

#1907 fix: fix a11y check task (selenium firefox issue)
  bin/check-a11y.js
  package-lock.json
  package.json
Labels: bug, cli, internal-utils

#1902 feat(snackbar): init snackbar data flow logic
  package-lock.json
  packages/components/snackbar/package.json
  packages/components/snackbar/src/SnackBarItemContext.tsx
  packages/components/snackbar/src/Snackbar.doc.mdx
  packages/components/snackbar/src/Snackbar.stories.tsx
  packages/components/snackbar/src/Snackbar.styles.ts
  packages/components/snackbar/src/Snackbar.test.tsx
  packages/components/snackbar/src/Snackbar.tsx
  packages/components/snackbar/src/SnackbarItem.tsx
  packages/components/snackbar/src/index.ts
Labels: component

#1915 fix(dropdown): fixing empty value items selection
  package-lock.json
  packages/components/dropdown/src/Dropdown.stories.tsx
  packages/components/dropdown/src/useDropdown.ts
Labels: bug

#1909 fix(badge): badge outline now utilizes "surface" token
  packages/components/badge/src/BadgeItem.styles.tsx
Labels: bug, component
